### ISSUE TITLE
URLs in code blocks and snippets urls are converted to links

### ISSUE THREAD

**Issue by stvnjacobs** [linode/docs#1278]
It doesn't seem right that URLs in `<pre>` and `<code>` blocks are converted to links.

Examples include `example.com` and the snippet in the guide linked below.

```
example.com {
root /var/www/my-website
}
```
https://linode.com/docs/web-servers/caddy/install-and-configure-caddy-on-centos-7/#configure-the-caddyfile

**Comment by GuessWhoSamFoo** [comment]
Odd; can't reproduce in a development environment

**Comment by kcraig34** [comment]
Might this be an off-shoot of Hugo interpreting formatting markers that, instead of shadow-blocking the text, ends up creating a link?
If not, might it be from a default interpretation of ---.com by Hugo that triggers a link?
Regardless, I can't see the reason, at this time, to spend lots of time debugging this, unless it affects our overall publishing efforts.
So, if you can't solve quickly, note, remember, and move on. (It doesn't seem like this is a critical bug that could bring down a user's session.)
We've got a new set of cards attending to CS team's bugs/recommendations. We can address this in a future iteration - again, unless solving this is essential to our capability to publish docs.
Thanks, @GuessWhoSamFoo

**Comment by stvnjacobs** [comment]
The rendered links have a `vglnk` class which I traced back to disqus sources on the page.  I found a blog post which found the same and identifies disqus affiliate links are to blame.

[1]: https://www.cleversprocket.com/disqus-is-parsing-your-dom-and-adding-affiliate-links/

**Comment by GuessWhoSamFoo** [comment]
Turned off affiliate links and cookie tracking via Disqus. Thanks for the help @stvnjacobs
