### ISSUE TITLE
How to Install Git on Linux, Mac or Windows Installation Error

### ISSUE THREAD

**Issue by saideepthik** [linode/docs#1430]
Link: https://linode.com/docs/development/version-control/how-to-install-git-on-linux-mac-and-windows/
## Issue
i'm using ubuntu unable to install git using sudo  command but it works in another pc what could be the problem in pc?

**Comment by GuessWhoSamFoo** [comment]
Could be a number of factors without more information like version, console output, etc. Probably could start with `sudo apt update`, `sudo apt upgrade`.

If there is a broken installation, possibly `sudo apt install -f` for repairing broken links.

For future reference, please use Github for reporting issues within the documentation rather than case specific problems.
