### ISSUE TITLE
Deprecated with no explanation

### ISSUE THREAD

**Issue by jjok** [linode/docs#2446]
A lot of these articles seem to be deprecated, but they don't have an explanation of why.

Could each one include a sentence/paragraph as to why, and links to any articles that supercede the deprecated one?

**Comment by Guaris** [comment]
Usually, we deprecate guides when they reach a certain age and add a link to the text once a new guide is created. We leave the deprecated guides on the website so that people still have a chance to use them. Sometimes, our readers use legacy operating systems and still use the guides to troubleshoot. 

If at any time you want to fix or update a guide, feel free, we would even send you swag for doing it. 
https://www.linode.com/docs/find-this-guide-on-github/

**Comment by Guaris** [comment]
It usually means that it is the only article we have on the subject. It's more a 'use at your own risk'.

**Comment by jjok** [comment]
I would have thought something like "How to install Docker and deploy a LAMP Stack" is a fairly common use case.
