### ISSUE TITLE
Email with Postfix, Dovecot, and MySQL Proposed Changes

### ISSUE THREAD

**Issue by dont-panic-42** [linode/docs#2507]
Link: https://linode.com/docs/email/postfix/email-with-postfix-dovecot-and-mysql/
## Issue

After following through this guide on a clean Debian 9 Linode, I was seeing the following errors in `/var/log/mail.log`:

    postfix/sendmail[7832]: fatal: open /etc/postfix/main.cf: Permission denied

I had set permissions exactly as described in this guide ("Master Program Settings", part 3, `chmod -R o-rwx /etc/postfix`), like so:

    -rw-r-----  1 root root  3532 May 25 16:18 main.cf

I tried changing group to `postfix`, but that didn't help.  After much Googling and experimenting I came across a reference to this command:

    postfix set-permissions

This solved the problem for me, resetting permissions on several files in `/etc/postfix/` which the `chmod` above had changed.  `main.cf` now looks like (group `postfix` is probably bcs I did `chgrp`, not bcs of this command):

    -rw-r--r--  1 root postfix  3532 May 25 16:18 main.cf

The errors have gone, so I think this was the problem.

## Suggested Fix

The guide describes doing `chmod -R o-rwx /etc/postfix` - is it really correct?

**Comment by Mqrius** [comment]
From what I understand, the postfix master process runs as root by default, which is necessary to bind ports below 1024. The master process spawns processes with lower privileges where necessary.

I'm assuming the master process is the one that reads the config files, and that's why it works out in the end. I don't know why your setup didn't work. I followed the guide just now and didn't have any trouble with it, including the suggested chmods.

**Comment by Rajakavitha1** [comment]
@dont-panic-42 Marking this issue as closed because we are not able to reproduce the issue that you mentioned. However, please feel free to reopen the issue if it still persists.
