### ISSUE TITLE
Configure Your Linode for Reverse DNS (rDNS) Proposed Changes

### ISSUE THREAD

**Issue by jsoref** [linode/docs#2512]
Link: https://linode.com/docs/networking/dns/configure-your-linode-for-reverse-dns/
## Issue

There was an old ui https://manager.linode.com/linodes which works reasonably well for basic management of Linodes.

This page doesn't hint that one needs to use the new url https://cloud.linode.com/ in order to see a UI which corresponds to the documentation (other pages mention cloud manager, but not sufficiently prominently to make it clear that's what's going on).

It's true that there's a link on the top of manager "Linode Cloud Manager has arrived!" but that didn't actually explain what it was/why I should pay attention.

## Suggested Fix
1. Mention that the steps start with the cloud manager (and include the url)
1. The banner at the top of manager should be adjusted to give a better indication that it's the replacement UI with more features.

**Comment by Rajakavitha1** [comment]
Hi @jsoref !!!
There is a note on https://linode.com/docs/networking/dns/configure-your-linode-for-reverse-dns/  that reads:
The Linode Classic Manager
If you're using the Linode Classic Manager instead of the new Cloud Manager, you can still view the Classic Manager version of this Configure Your Linode for Reverse DNS (rDNS) guide.

**Comment by Guaris** [comment]
@jsoref Feel free to open up this issue again if this does not solve your problem.
