### ISSUE TITLE
Email with Postfix, Dovecot, and MySQL Proposed Changes

### ISSUE THREAD

**Issue by Mqrius** [linode/docs#2524]
Link: https://linode.com/docs/email/postfix/email-with-postfix-dovecot-and-mysql/#test-email-with-mailutils
## Issue
mail(1) doesn't recognize Maildir format when given `-f` option

To check if everything is set up correctly, the guide tells users to run the following command:
`sudo mail -f /var/mail/vhosts/example.com/email1`

However, this returns:
`mail: /var/mail/vhosts/example.com/email1: Is a directory`

## Suggested Fix
I don't have a good fix. The guide still works to set up everything correctly, it just can't be tested with this method it seems.

Choosing an alternative for mailx might work as mentioned [here](https://unix.stackexchange.com/questions/172316/debian-exim-maildir-and-mail), but that seems cumbersome for only testing receipt of mail.

**Comment by wildmanonline** [comment]
Thanks for the issue and apologies for the delay here. Since this report, the guide has been validated and updated quite a few times with no mention of any issues with that command. Reading through the instructions, the username and domain name need to be replaced based on how things have been configured. Perhaps that was the reason for your error. If not, don't hesitate to reply back. For now, marking this issue as closed.

**Comment by mun3** [comment]
> Thanks for the issue and apologies for the delay here. Since this report, the guide has been validated and updated quite a few times with no mention of any issues with that command. Reading through the instructions, the username and domain name need to be replaced based on how things have been configured. Perhaps that was the reason for your error. If not, don't hesitate to reply back. For now, marking this issue as closed.

The issue persists.
