### ISSUE TITLE
How to Deploy Microservices with Docker Proposed Changes

### ISSUE THREAD

**Issue by srinivasnaganand** [linode/docs#2587]
Link: https://linode.com/docs/applications/containers/deploying-microservices-with-docker/
## Issue

While running "docker-compose up"  we are getting the below error
 Error: pg_config executable not found.

    pg_config is required to build psycopg2 from source.  Please add the directory
    containing pg_config to the $PATH or specify the full executable path with the
    option:

        python setup.py build_ext --pg-config /path/to/pg_config build ...

    or with the pg_config option in 'setup.cfg'.

    If you prefer to avoid building psycopg2 from source, please install the PyPI
    'psycopg2-binary' package instead.

    For further information please check the 'doc/src/install.rst' file (also at
    <http://initd.org/psycopg/docs/install.html>).

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ilsp5le4/psycopg2/
You are using pip version 9.0.1, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
ERROR: Service 'flaskapp' failed to build: The command '/bin/sh -c pip install --no-cache-dir -r requirements.txt' returned a non-zero code: 1
root@microservices:~/flask-microservice#

**Comment by Rajakavitha1** [comment]
Hi @srinivasnaganand 

This issue is now addressed in https://github.com/linode/docs/pull/3053

Here's a preview of the updated guide: https://deploy-preview-3053--nostalgic-ptolemy-b01ab8.netlify.com/applications/containers/deploying-microservices-with-docker/

Marking this issue as closed now. Please feel free to reopen the issue if any other updates need to be made.
