### ISSUE TITLE
How to Install and Configure FastCGI and PHP-FPM on Debian 10 Proposed Changes

### ISSUE THREAD

**Issue by StephenLittBelch** [linode/docs#3311]
Link: https://linode.com/docs/web-servers/apache/how-to-install-and-configure-fastcgi-and-php-fpm-on-debian-10/
## Issue
Article describes the use of _mod_proxy_fcgi_ and _php-fpm_, but mentions _mod_fcgid_ (an external module) in the first few paragraphs and “Install mod_fcgid and PHP-FPM” section.
## Suggested Fix
Update references and installation instructions for _mod_fcgid_ to _proxy_fcgi module_ or _mod_proxy_fcgi_.

**Comment by Rajakavitha1** [comment]
Hi @StephenLittBelch  Thank you for the feedback. I just read the docs and it reads: "Load the mod_proxy and mod_proxy_fcgi modules by editing your main Apache configuration to add the lines included in the example. Both these modules are included by default in your Apache installation, but the must be explicitly loaded in order to use them. You will need these modules to proxy requests through mod_fcgid to your socket."  hope that clarifies the need for references. Closing this issue for now. please feel free to reopen if any other changes need to me made.
