### ISSUE TITLE
How to Use Server-Side Encryption with Linode Object Storage Proposed Changes

### ISSUE THREAD

**Issue by zishanj** [linode/docs#4382]
Link: https://www.linode.com/docs/guides/server-side-encryption/
## Issue
This python script does not encrypt the file and the file is stored unencrypted on the Linode ObjectStorage.

**Comment by Rajakavitha1** [comment]
hi @zishanj !!! We validated the steps in the guide  on Ubuntu with 3.7+ and the steps work fine. However, because python 2.7 has reached end of life there may be issues with the python 2.7 version. We just updated the guide accordingly.
Closing this issue for now. Please feel free to reopen if any other changes need t be made.
