### ISSUE TITLE
Tuning your apache server: specifically mention mod_php in the prefork section

### ISSUE THREAD

**Issue by dwfreed** [linode/docs#564]
Most people don't realize mod_php is not threadsafe, so I would mention it explicitly.

**Comment by alexfornuto** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Tuning your apache server: specifically mention mod_php in the prefork section](https://trello.com/c/Fzju60Od/89-tuning-your-apache-server-specifically-mention-mod-php-in-the-prefork-section)

**Comment by pbzona** [comment]
Hey @dwfreed, thanks for raising this issue. I've created a pull request to address it here:

https://github.com/linode/docs/pull/624

While I had the doc open, I went ahead and rewrote each MPM section to make them a bit easier to read. It seems you know Apache quite well (since you caught this omission) so any feedback you have on my rewrites would be more than welcome. Thanks again!

**Comment by cwlinode** [comment]
Thank you for bringing this up. We'll have the updated guide published shortly. Closing.
