### ISSUE TITLE
Sinatra Framework and nginx on Debian 6 (Squeeze) Proposed Changes

### ISSUE THREAD

**Issue by sailpwnz** [linode/docs#6089]
Hi, can you do the setup for Debian 11 and ruby 3.20

Link: https://www.linode.com/docs/guides/sinatra-framework-and-nginx-on-debian-6-squeeze/

**Comment by Rajakavitha1** [comment]
Hi @sailpwnz!!! You may want to post this question on https://www.linode.com/community/questions/, you Linode community you have a large audience who may be able to help you with your specific question or provide alternatives. Closing this issue for now because it is not related to the documentation.
